/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 Bed King.glb Chair.glb Closet.glb Kitchen Fridge Small.glb Kitchen Sink.glb Oven.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/BedKing.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Bed_King_1.geometry} material={materials.DarkRed} />
        <mesh geometry={nodes.Bed_King_2.geometry} material={materials.White} />
        <mesh geometry={nodes.Bed_King_3.geometry} material={materials.Red} />
        <mesh geometry={nodes.Bed_King_4.geometry} material={materials.Grey} />
        <mesh geometry={nodes.Bed_King_5.geometry} material={materials.Wood} />
      </group>
    </group>
  )
}

useGLTF.preload('/BedKing.glb')
