/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ../public/Couch.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Couch.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['Node-Mesh'].geometry} material={materials.Traditiona} />
      <mesh geometry={nodes['Node-Mesh_1'].geometry} material={materials.Traditiona_1} />
    </group>
  )
}

useGLTF.preload('/Couch.glb')
