/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ../public/FridgeAndCooker.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/FridgeAndCooker.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.mesh610829822.geometry} material={materials.mat21} />
      <mesh geometry={nodes.mesh610829822_1.geometry} material={materials.mat22} />
      <mesh geometry={nodes.mesh610829822_2.geometry} material={materials.mat18} />
      <mesh geometry={nodes.mesh610829822_3.geometry} material={materials.mat15} />
      <mesh geometry={nodes.mesh610829822_4.geometry} material={materials.mat23} />
      <mesh geometry={nodes.mesh610829822_5.geometry} material={materials.mat5} />
      <mesh geometry={nodes.mesh1390275597.geometry} material={materials.mat5} />
      <mesh geometry={nodes.mesh1390275597_1.geometry} material={materials.mat21} />
      <mesh geometry={nodes.mesh1390275597_2.geometry} material={materials.mat22} />
      <mesh geometry={nodes.mesh1390275597_3.geometry} material={materials.mat16} />
      <mesh geometry={nodes.mesh1390275597_4.geometry} material={materials.mat23} />
      <mesh geometry={nodes.mesh1390275597_5.geometry} material={materials.mat17} />
      <mesh geometry={nodes.mesh1390275597_6.geometry} material={materials.mat12} />
      <mesh geometry={nodes.mesh1684725353.geometry} material={materials.mat17} />
      <mesh geometry={nodes.mesh1684725353_1.geometry} material={materials.mat20} />
      <mesh geometry={nodes.mesh1015041580.geometry} material={materials.mat15} />
      <mesh geometry={nodes.mesh1015041580_1.geometry} material={materials.mat23} />
      <mesh geometry={nodes.mesh1015041580_2.geometry} material={materials.mat16} />
    </group>
  )
}

useGLTF.preload('/FridgeAndCooker.glb')
