/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ../public/GardenLounger.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/GardenLounger.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh1_Group2_Component_5_1_Group1_Model.geometry} material={materials._NavajoWhite_} />
      <mesh geometry={nodes.Mesh2_Group3_Component_5_1_Group1_Model.geometry} material={materials._NavajoWhite_} />
      <mesh geometry={nodes.Mesh3_Group3_Component_5_1_Group1_Model.geometry} material={materials._NavajoWhite_} />
      <mesh geometry={nodes.Mesh4_Component_5_1_Group1_Model.geometry} material={materials._NavajoWhite_} />
      <mesh geometry={nodes.Mesh5_Component_5_1_Group1_Model.geometry} material={materials._NavajoWhite_} />
      <mesh geometry={nodes.Mesh6_Component_5_1_Group1_Model.geometry} material={materials._NavajoWhite_} />
      <mesh geometry={nodes.Mesh7_Group4_Component_5_2_Group1_Model.geometry} material={materials._NavajoWhite_} />
      <mesh geometry={nodes.Mesh8_Group5_Component_5_2_Group1_Model.geometry} material={materials._NavajoWhite_} />
      <mesh geometry={nodes.Mesh9_Group5_Component_5_2_Group1_Model.geometry} material={materials._NavajoWhite_} />
      <mesh geometry={nodes.Mesh10_Component_5_2_Group1_Model.geometry} material={materials._NavajoWhite_} />
      <mesh geometry={nodes.Mesh11_Component_5_2_Group1_Model.geometry} material={materials._NavajoWhite_} />
      <mesh geometry={nodes.Mesh12_Component_5_2_Group1_Model.geometry} material={materials._NavajoWhite_} />
    </group>
  )
}

useGLTF.preload('/GardenLounger.glb')
