/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ../public/KitchenFridgeSmall.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/KitchenFridgeSmall.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.kitchenFridgeSmall_2.geometry} material={materials.metalLight} />
      <mesh geometry={nodes.kitchenFridgeSmall_2_1.geometry} material={materials.metalDark} />
      <mesh geometry={nodes.kitchenFridgeSmall_3.geometry} material={materials.metalDark} />
      <mesh geometry={nodes.kitchenFridgeSmall_3_1.geometry} material={materials.metalLight} />
      <mesh geometry={nodes.doorFridge_1.geometry} material={materials.metalLight} />
      <mesh geometry={nodes.doorFridge_1_1.geometry} material={materials.glass} />
      <mesh geometry={nodes.doorFridge_1_2.geometry} material={materials.metal} />
    </group>
  )
}

useGLTF.preload('/KitchenFridgeSmall.glb')
