/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 walls.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/walls.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Body_01.geometry} material={nodes.Body_01.material} />
      <mesh geometry={nodes.Body_02.geometry} material={nodes.Body_02.material} />
    </group>
  )
}

useGLTF.preload('/walls.gltf')
